image: golang:latest

stages:
  - validate

fmt:
  stage: validate
  script:
    - gofmt -l -s -e .
    - exit $(gofmt -l -s -e . | wc -l)

lint:
  stage: validate
  script:
    - go get -u golang.org/x/lint/golint
    - golint -set_exit_status

vet:
  stage: validate
  script:
    - go vet -composites=false ./...

test:
  stage: validate
  script:
    - go test -race -v ./...
